# Análise de Vendas de Carros: Transformando Dados em Insights Automotivos

# Extraction

In [1]:
import pandas as pd

df = pd.read_csv("Car_sales.csv")
display(df)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

# Transform

In [2]:
# Removendo NaN
df.fillna(0, inplace=True)

In [3]:
# MODELOS MAIS POPULARES
# vendas totais para cada modelo
modelo_vendas = df.groupby('Model')['Sales_in_thousands'].sum().reset_index()
# Modelos por vendas em ordem decrescente
modelo_vendas = modelo_vendas.sort_values(by='Sales_in_thousands', ascending=False)
# Crie uma nova coluna 'Popular_Model' que indica se o modelo está entre os mais populares
top_modelos = 5  # Defina o número de modelos mais populares que você deseja identificar
modelo_vendas['Popular_Model'] = modelo_vendas.index < top_modelos
# Junte a nova coluna de volta ao DataFrame original
df = df.merge(modelo_vendas[['Model', 'Popular_Model']], on='Model', how='left')
display(df)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor,Popular_Model
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150,False
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778,False
2,Acura,CL,14.114,18.225,Passenger,0.00,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,0.000000,False
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779,False
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,0.000,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812,False
153,Volvo,S70,15.245,0.000,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495,False
154,Volvo,V70,17.531,0.000,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978,False
155,Volvo,C70,3.493,0.000,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357,False
156,Volvo,S80,18.969,0.000,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655,False

In [4]:
# PESO / POTÊNCIA DOS CARROS
# Coluna peso em kg
df['Weight_kg'] = df['Curb_weight'] / 2.20462
df['Weight_kg'] = df['Weight_kg'].round(3)
# Crie a nova coluna 'Peso_Por_Potencia' 
df['Peso_Por_Potencia'] = df['Weight_kg'] / df['Horsepower'] * 1000 # x1000 para formatar o resultado
df['Peso_Por_Potencia'] = df['Peso_Por_Potencia'].round(1)
display(df)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor,Popular_Model,Weight_kg,Peso_Por_Potencia
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150,False,1.197,8.6
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778,False,1.595,7.1
2,Acura,CL,14.114,18.225,Passenger,0.00,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,0.000000,False,1.574,7.0
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779,False,1.746,8.3
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639,False,1.360,9.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,0.000,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812,False,1.380,8.6
153,Volvo,S70,15.245,0.000,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495,False,1.455,8.7
154,Volvo,V70,17.531,0.000,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978,False,1.478,8.8
155,Volvo,C70,3.493,0.000,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357,False,1.633,6.9
156,Volvo,S80,18.969,0.000,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655,False,1.633,8.1

# Load

In [5]:
df.to_csv('Car_sales_insights.csv', index=False)